name: pycheckout
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates
  - certifi=2020.12.5
  - ld_impl_linux-64
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libopenblas=0.3.13
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1k
  - pandas=1.2.4
  - pip=21.0.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - pytz=2021.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
