name: pycheckout
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - intel-openmp=2020.2
  - libffi=3.3
  - libflang=5.0.0
  - libopenblas=0.3.13
  - llvm-meta=5.0.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.0.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openmp=5.0.0
  - openssl=1.1.1k
  - pandas=1.2.4
  - pip=21.0.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - pytz=2021.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tzdata=2020f
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
